#!/usr/bin/env python3
"""Render docs/methodology/catalogue.md from data/catalogue.json (+ activity from .claude/memory/sources.tsv / history.tsv).

data/catalogue.json is the source of truth for per-repo facts (one object per repo, 15 fields, `functions` is a
list of tags). Edit it (or merge rows), then re-run this script.

usage: gen_catalogue.py [--merge rows.tsv|rows.json ...]
  --merge  upsert rows (TSV with the 15-column header or no header, or a JSON list of objects) into
           data/catalogue.json before rendering; rows are matched on `slug`.
Warns about slugs pinned in sources.tsv without a row, and rows without a pin.
"""
import csv, json, os, subprocess, collections, sys

ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'],
                               cwd=os.path.dirname(os.path.abspath(__file__)), text=True).strip()
MEM = os.path.join(ROOT, '.claude/memory')
SRC = os.path.join(ROOT, 'original_sources')

def read_tsv(p):
    with open(p) as f:
        return list(csv.DictReader(f, delimiter='\t'))

FIELDS = ['slug', 'kind', 'name', 'fork_of', 'ulx3s_path', 'fpga', 'toolchain', 'hdl', 'license', 'board_rev',
          'functions', 'reuse', 'notes', 'tests', 'make_tests']
CAT_JSON = os.path.join(ROOT, 'data', 'catalogue.json')


def norm_row(r):
    r = {k: (r.get(k) if r.get(k) is not None else '') for k in FIELDS}
    if isinstance(r['functions'], str):
        r['functions'] = [t.strip() for t in r['functions'].split(',') if t.strip()]
    return r


def load_rows(path):
    if path.endswith('.json'):
        rows = json.load(open(path))
        return rows['repos'] if isinstance(rows, dict) else rows
    lines = [l for l in open(path).read().split('\n') if l.strip()]
    if lines and lines[0].split('\t')[0] == 'slug':
        lines = lines[1:]
    out = []
    for l in lines:
        f = l.split('\t')
        if len(f) != len(FIELDS):
            sys.exit(f'{path}: {f[0]} has {len(f)} fields, expected {len(FIELDS)}')
        out.append(dict(zip(FIELDS, f)))
    return out


doc = json.load(open(CAT_JSON))
by_slug = {r['slug']: norm_row(r) for r in doc['repos']}
args = sys.argv[1:]
while args:
    a = args.pop(0)
    if a == '--merge':
        for r in load_rows(args.pop(0)):
            r = norm_row(r)
            print(('updated ' if r['slug'] in by_slug else 'added ') + r['slug'])
            by_slug[r['slug']] = r
    else:
        sys.exit(__doc__)
doc['repos'] = [by_slug[k] for k in sorted(by_slug)]
with open(CAT_JSON, 'w') as f:
    json.dump(doc, f, indent=1, ensure_ascii=False)
    f.write('\n')
cat = [dict(r, functions=', '.join(r['functions'])) for r in doc['repos']]
pins = {r['slug']: r for r in read_tsv(os.path.join(MEM, 'sources.tsv'))}
hist_p = os.path.join(MEM, 'history.tsv')
hist = {r['slug']: r for r in read_tsv(hist_p)} if os.path.exists(hist_p) else {}
for s in sorted(set(pins) - set(by_slug)):
    print(f'WARN {s}: pinned in sources.tsv but no catalogue row', file=sys.stderr)
for s in sorted(set(by_slug) - set(pins)):
    print(f'WARN {s}: catalogue row but not pinned in sources.tsv', file=sys.stderr)

def git(slug, *args):
    d = os.path.join(SRC, slug)
    if not os.path.isdir(os.path.join(d, '.git')):
        return ''
    try:
        return subprocess.check_output(['git', '-C', d, *args], text=True, stderr=subprocess.DEVNULL).strip()
    except subprocess.CalledProcessError:
        return ''

def activity(slug):
    # clones are shallow (1 commit): history stats come from history.tsv
    h = hist.get(slug, {})
    last = pins.get(slug, {}).get('upstream_date', '')
    return h.get('first_commit', '?'), last, h.get('commits', '?')

def esc(s):
    return s.replace('|', '\\|')

def tc_short(t):
    t = t.lower()
    if t.startswith('both'): return 'both'
    if t.startswith('diamond'): return 'diamond'
    if t.startswith('open'): return 'open'
    if t.startswith('unknown'): return 'unknown'
    return 'n/a'

GROUPS = [
    ('Board, tools and infrastructure', lambda r: r['kind'] in ('pcb', 'host-tool', 'toolchain', 'binaries', 'software', 'esp32-software', 'os-software', 'archive')),
    ('Example collections and education', lambda r: r['kind'] in ('examples', 'education') or 'examples' in r['functions'].split(', ')[:1]),
    ('SoCs, CPUs and Linux', lambda r: any(t in r['functions'] for t in ('soc-cpu', 'linux', 'hdl-language')) and not any(t in r['functions'] for t in ('retro-computer', 'retro-console', 'retro-arcade'))),
    ('Retro computers, consoles and arcade', lambda r: any(t in r['functions'] for t in ('retro-computer', 'retro-console', 'retro-arcade'))),
    ('Other gateware (video, audio, radio, flash, instruments)', lambda r: True),
]

placed, sections = set(), collections.OrderedDict((g, []) for g, _ in GROUPS)
for g, pred in GROUPS:
    for r in cat:
        if r['slug'] not in placed and pred(r):
            sections[g].append(r); placed.add(r['slug'])

out = ['# Full catalogue', '',
       'Generated by `.claude/skills/review-gateware-project/gen_catalogue.py` from '
       '[`data/catalogue.json`](https://github.com/kelu124/lattice-verilog-projects/blob/main/data/catalogue.json). '
       'Do not edit by hand.', '',
       '**Toolchain**: `open` = yosys + nextpnr-ecp5 + ecppack (incl. via apio/LiteX/ghdl plugin), '
       '`diamond` = Lattice Diamond, `both` = both build paths exist. '
       '**License** `none found` = no license file/header found (all rights reserved by default; ask the author before reusing). '
       '**Fork** column: which copy to prefer when several clones exist.', '']

tc = collections.Counter(tc_short(r['toolchain']) for r in cat if r['kind'] in ('gateware', 'examples', 'education', 'mixed'))
lic_none = sum(1 for r in cat if r['license'].lower().startswith('none'))
def make_run(r):
    v = (r.get('make_tests') or '').strip()
    return v and not v.lower().startswith(('none', 'unknown'))

has_tests = sum(1 for r in cat if r.get('tests', 'none found').lower() != 'none found')
not_ecp5 = sorted(r['slug'] for r in cat if 'NOT ECP5' in r['fpga'])
out += ['## At a glance', '',
        f'- {len(cat)} repositories catalogued.',
        f'- Gateware toolchains: ' + ', '.join(f'{k} {v}' for k, v in tc.most_common()) + '.',
        f'- {lic_none} repositories have no license found.',
        f'- {has_tests} repositories have some detected testbench/simulation setup (heuristic scan; see "Testbenches and simulation" below).',
        f'- {sum(1 for r in cat if make_run(r))} repositories have a Makefile target that runs a testbench/simulation/formal check (`make_tests`).',
        f'- {len(not_ecp5)} repositories target a **non-ECP5** FPGA (iCE40 UP5K etc., marked `NOT ECP5` in the FPGA column): '
        + (', '.join(not_ecp5) or 'none') + '.',
        '']

for g, rs in sections.items():
    if not rs: continue
    out += [f'## {g}', '',
            '| Repo | What | FPGA | Toolchain | HDL | License | Active (first → last, commits) | Fork / preferred copy |',
            '|---|---|---|---|---|---|---|---|']
    for r in rs:
        f, l, n = activity(r['slug'])
        url = pins.get(r['slug'], {}).get('url', '').rstrip('/')
        out.append('| ' + ' | '.join(esc(x) for x in [
            f"[{r['slug']}]({url})", r['name'], r['fpga'], r['toolchain'], r['hdl'], r['license'],
            f"{f} → {l}, {n}", r['fork_of']]) + ' |')
    out.append('')

tested = [r for r in cat if r.get('tests', 'none found').lower() != 'none found' or make_run(r)]
out += ['## Testbenches and simulation', '',
        'Heuristic scan (`.claude/skills/review-gateware-project/scan_tests.sh`, 2026-09-27) over each shallow '
        'clone for test/sim directories (`tb/`, `test/`, `sim/`, ...), testbench-named files '
        '(`*_tb.v`, `tb_*.vhd`, `*_test.py`, ...) and simulator mentions (iverilog, Verilator, GHDL, cocotb, '
        'VUnit) in build scripts. It is a name/path heuristic, not proof the tests run or pass — verify before '
        'relying on one. Repos not listed here had nothing matching.', '',
        'The **Run by make** column (`make_tests`, 2026-09-28) comes from `scan_make_tests.py` candidates checked by '
        'hand-reading the Makefiles: the make command, simulator and testbench files a target actually runs. Lint-only '
        'and synthesis-only uses of simulators are excluded. Nothing was executed.', '',
        '| Repo | Detected test/sim setup | Run by make |', '|---|---|---|']
for r in tested:
    out.append(f"| [{r['slug']}]({pins.get(r['slug'], {}).get('url', '').rstrip('/')}) | {esc(r['tests'])} | {esc(r.get('make_tests') or '')} |")
out.append('')

out += ['## Functions and reusable blocks', '',
        'Per repo: function tags, where the ULX3S build lives, the constraint file, reusable cores, tests, and notes.', '']
for r in cat:
    out += [f"### {r['slug']}",
            f"- **Functions**: {r['functions']}",
            f"- **ULX3S build**: {r['ulx3s_path']} (LPF: {r['board_rev']})",
            f"- **Reuse**: {r['reuse']}",
            f"- **Tests**: {r.get('tests', 'unknown')}",
            f"- **Notes**: {r['notes']}", '']

# Function index
idx = collections.defaultdict(list)
for r in cat:
    for t in r['functions'].split(','):
        t = t.strip().replace('NEW:', '')
        if t: idx[t].append(r['slug'])
out += ['## Index by function', '']
for t in sorted(idx):
    out.append(f"- **{t}**: " + ', '.join(sorted(idx[t])))
out.append('')

FRONT = ('---\ntitle: "Full catalogue"\nparent: "Methodology"\nnav_order: 10\n---\n'
         '<!-- Generated from data/catalogue.json by .claude/skills/review-gateware-project/gen_catalogue.py; do not edit. -->\n\n')
os.makedirs(os.path.join(ROOT, 'docs/methodology'), exist_ok=True)
with open(os.path.join(ROOT, 'docs/methodology/catalogue.md'), 'w') as f:
    f.write(FRONT + '{% raw %}\n' + '\n'.join(out) + '\n{% endraw %}\n')
print(f'wrote docs/methodology/catalogue.md ({len(cat)} repos)')
