#!/usr/bin/env python3
"""Render docs/catalogue.md from .claude/memory/catalogue.tsv (+ activity from sources.tsv / local clones).

catalogue.tsv is the source of truth for per-repo facts; edit it, then re-run this script.
"""
import csv, os, subprocess, collections

ROOT = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'],
                               cwd=os.path.dirname(os.path.abspath(__file__)), text=True).strip()
MEM = os.path.join(ROOT, '.claude/memory')
SRC = os.path.join(ROOT, 'original_sources')

def read_tsv(p):
    with open(p) as f:
        return list(csv.DictReader(f, delimiter='\t'))

cat = read_tsv(os.path.join(MEM, 'catalogue.tsv'))
pins = {r['slug']: r for r in read_tsv(os.path.join(MEM, 'sources.tsv'))}

def git(slug, *args):
    d = os.path.join(SRC, slug)
    if not os.path.isdir(os.path.join(d, '.git')):
        return ''
    try:
        return subprocess.check_output(['git', '-C', d, *args], text=True, stderr=subprocess.DEVNULL).strip()
    except subprocess.CalledProcessError:
        return ''

def activity(slug):
    first = git(slug, 'log', '--reverse', '--format=%cs').split('\n')[0] if git(slug, 'rev-parse', 'HEAD') else ''
    n = git(slug, 'rev-list', '--count', 'HEAD')
    last = pins.get(slug, {}).get('upstream_date', '')
    return first, last, n

def esc(s):
    return s.replace('|', '\\|')

def tc_short(t):
    t = t.lower()
    if t.startswith('both'): return 'both'
    if t.startswith('diamond'): return 'diamond'
    if t.startswith('open'): return 'open'
    if t.startswith('unknown'): return 'unknown'
    return 'n/a'

GROUPS = [
    ('Board, tools and infrastructure', lambda r: r['kind'] in ('pcb', 'host-tool', 'toolchain', 'binaries', 'software', 'esp32-software', 'os-software', 'archive')),
    ('Example collections and education', lambda r: r['kind'] in ('examples', 'education') or 'examples' in r['functions'].split(', ')[:1]),
    ('SoCs, CPUs and Linux', lambda r: any(t in r['functions'] for t in ('soc-cpu', 'linux', 'hdl-language')) and not any(t in r['functions'] for t in ('retro-computer', 'retro-console', 'retro-arcade'))),
    ('Retro computers, consoles and arcade', lambda r: any(t in r['functions'] for t in ('retro-computer', 'retro-console', 'retro-arcade'))),
    ('Other gateware (video, audio, radio, flash, instruments)', lambda r: True),
]

placed, sections = set(), collections.OrderedDict((g, []) for g, _ in GROUPS)
for g, pred in GROUPS:
    for r in cat:
        if r['slug'] not in placed and pred(r):
            sections[g].append(r); placed.add(r['slug'])

out = ['# ULX3S project catalogue', '',
       'Generated by `.claude/skills/review-gateware-project/gen_catalogue.py` from `.claude/memory/catalogue.tsv`. '
       'Do not edit by hand.', '',
       '**Toolchain**: `open` = yosys + nextpnr-ecp5 + ecppack (incl. via apio/LiteX/ghdl plugin), '
       '`diamond` = Lattice Diamond, `both` = both build paths exist. '
       '**License** `none found` = no license file/header found (all rights reserved by default; ask the author before reusing). '
       '**Fork** column: which copy to prefer when several clones exist.', '']

tc = collections.Counter(tc_short(r['toolchain']) for r in cat if r['kind'] in ('gateware', 'examples', 'education', 'mixed'))
lic_none = sum(1 for r in cat if r['license'].lower().startswith('none'))
out += ['## At a glance', '',
        f'- {len(cat)} repositories catalogued.',
        f'- Gateware toolchains: ' + ', '.join(f'{k} {v}' for k, v in tc.most_common()) + '.',
        f'- {lic_none} repositories have no license found.', '']

for g, rs in sections.items():
    if not rs: continue
    out += [f'## {g}', '',
            '| Repo | What | FPGA | Toolchain | HDL | License | Active (first → last, commits) | Fork / preferred copy |',
            '|---|---|---|---|---|---|---|---|']
    for r in rs:
        f, l, n = activity(r['slug'])
        url = pins.get(r['slug'], {}).get('url', '').rstrip('/')
        out.append('| ' + ' | '.join(esc(x) for x in [
            f"[{r['slug']}]({url})", r['name'], r['fpga'], r['toolchain'], r['hdl'], r['license'],
            f"{f} → {l}, {n}", r['fork_of']]) + ' |')
    out.append('')

out += ['## Functions and reusable blocks', '',
        'Per repo: function tags, where the ULX3S build lives, the constraint file, reusable cores, and notes.', '']
for r in cat:
    out += [f"### {r['slug']}",
            f"- **Functions**: {r['functions']}",
            f"- **ULX3S build**: {r['ulx3s_path']} (LPF: {r['board_rev']})",
            f"- **Reuse**: {r['reuse']}",
            f"- **Notes**: {r['notes']}", '']

# Function index
idx = collections.defaultdict(list)
for r in cat:
    for t in r['functions'].split(','):
        t = t.strip().replace('NEW:', '')
        if t: idx[t].append(r['slug'])
out += ['## Index by function', '']
for t in sorted(idx):
    out.append(f"- **{t}**: " + ', '.join(sorted(idx[t])))
out.append('')

with open(os.path.join(ROOT, 'docs/catalogue.md'), 'w') as f:
    f.write('\n'.join(out))
print(f'wrote docs/catalogue.md ({len(cat)} repos)')
